### ISSUE TITLE
How Decorate Namespaced Models?

### ISSUE THREAD

**Issue by wbotelhos** [amatsuda/active_decorator#121]
Model:

```
class Promoter
  class Role < ApplicationRecord
  end
end
```

Decorator:

```
class Promoter
  class RoleDecorator
    def _permissions; end
  end
end
```

Error:

```
NoMethodError:
    undefined method `_permissions' for #<Promoter::Role id: nil, ...
```

**Comment by amatsuda** [comment]
@wbotelhos `Promoter::RoleDecorator` has to be a module, not a class, so it can be mixed in to  `Role` class.
Also, there used to be a bug that nested class decoration was not working until dbc85d3bf9f7f7a23e0be218c2efa8feeb0a0387 (gem version 1.3.1). So please make sure you're bundling a newer version of this gem.
