### ISSUE TITLE
STI support on released version

### ISSUE THREAD

**Issue by tricknotes** [amatsuda/active_decorator#58]
@amatsuda 
Could you release a new version including 74828f1f585c444d3f8447546e99a4d27bd27f92 (from https://github.com/amatsuda/active_decorator/pull/33 )?
It seems not landed in v0.6.0 (the current latest release)

**Comment by tricknotes** [comment]
Thanks :sparkles: 
Now I confirmed [v0.7.0](https://rubygems.org/gems/active_decorator/versions/0.7.0) :heart:

**Comment by amatsuda** [comment]
Done :up: https://rubygems.org/gems/active_decorator/versions/0.7.0

**Comment by cafedomancer** [comment]
I've got v0.7.0.
Thank you so much!
