### ISSUE TITLE
Single Table Inheritance

### ISSUE THREAD

**Issue by glaucocustodio** [amatsuda/active_decorator#64]
Hi guys, if I have something like that:

`class User < ActiveRecord::Base; end`
`class Customer < User; end`

If I do have a `UserDecorator` but dont have a `CustomerDecorator`, shouldn't `active_decorator` load `UserDecorator` if my object is a `User` instance with `type="Customer"`?

Is it similar to https://github.com/drapergem/draper/issues/468?

Thanks.

**Comment by bradly** [comment]
@amatsuda Is this something you would accept a patch for?

**Comment by virtualkill** [comment]
@amatsuda NANDE!!!!!!!!!!! accept the damn patch

**Comment by virtualkill** [comment]
@amatsuda Have you no honor

**Comment by virtualkill** [comment]
@ursm NANDE!!!!!!!!!

**Comment by amatsuda** [comment]
This feature was implemented in #33 and already available in recent releases. Thanks!
