### ISSUE TITLE
ActiveDecorator vs Draper

### ISSUE THREAD

**Issue by wbotelhos** [amatsuda/active_decorator#93]
Hi @amatsuda ,

I'm using `draper` and found your gem that looks cleaner on dependency. Would you provide a comparison between both?

Automatically decorate the object couldn't be bad? Since it is not always we need the decorator methods? And what do you think about to use the same method name on decorator?

**Comment by amatsuda** [comment]
@wbotelhos I recommend you to try both. Then you'll find the answer yourself 😉
